create extension if not exists "moddatetime" with schema "extensions";

drop extension if exists "pg_net";


  create table "public"."BlogDetail" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "date" date,
    "media_url" text,
    "body" text,
    "location" text,
    "mood" text,
    "slug" text not null,
    "tags" text[],
    "summary" text not null,
    "gallery" text[]
      );



  create table "public"."Mails" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "email" text,
    "subject" text,
    "message" text,
    "date" timestamp with time zone default now()
      );



  create table "public"."Posts" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "slug" text not null,
    "date" date not null,
    "published" boolean,
    "media_url" text not null,
    "summary" text not null,
    "tags" text[]
      );


alter table "public"."Posts" enable row level security;


  create table "public"."ProjectDetail" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "image_url" text not null,
    "slug" text not null,
    "created_at" date not null,
    "description" text,
    "live_url" text not null,
    "repo_url" text not null,
    "role" text,
    "year" text not null,
    "tags" text[],
    "outcomes" text,
    "problem" text,
    "solution" text,
    "architecture" text,
    "technical_decisions" text,
    "challenges" text,
    "lessons_learned" text
      );



  create table "public"."Projects" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "git_url" text not null,
    "proj_url" text not null,
    "image_url" text not null,
    "date" date not null,
    "slug" text not null,
    "summary" text not null,
    "tags" text[]
      );



  create table "public"."Subscribers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "email" text,
    "confirmed" boolean
      );


alter table "public"."Subscribers" enable row level security;


  create table "public"."research_entries" (
    "id" uuid not null default gen_random_uuid(),
    "kind" text not null,
    "title" text not null,
    "subtitle" text,
    "year" text,
    "objective" text,
    "methods" text,
    "results" text,
    "reflection" text,
    "tags" text[],
    "link_url" text,
    "link_label" text,
    "display_order" integer not null default 0,
    "created_at" timestamp with time zone not null default now()
      );


CREATE UNIQUE INDEX "BlogDetail_gallery_key" ON public."BlogDetail" USING btree (gallery);

CREATE UNIQUE INDEX "BlogDetail_pkey" ON public."BlogDetail" USING btree (id);

CREATE UNIQUE INDEX "BlogDetail_slug_key" ON public."BlogDetail" USING btree (slug);

CREATE UNIQUE INDEX "BlogDetail_summary_key" ON public."BlogDetail" USING btree (summary);

CREATE UNIQUE INDEX "BlogDetail_tags_key" ON public."BlogDetail" USING btree (tags);

CREATE UNIQUE INDEX "BlogDetail_title_key" ON public."BlogDetail" USING btree (title);

CREATE UNIQUE INDEX "Mails_pkey" ON public."Mails" USING btree (id);

CREATE UNIQUE INDEX "Posts_date_key" ON public."Posts" USING btree (date);

CREATE UNIQUE INDEX "Posts_media_url_key" ON public."Posts" USING btree (media_url);

CREATE UNIQUE INDEX "Posts_pkey" ON public."Posts" USING btree (id);

CREATE UNIQUE INDEX "Posts_slug_key" ON public."Posts" USING btree (slug);

CREATE UNIQUE INDEX "Posts_summary_key" ON public."Posts" USING btree (summary);

CREATE UNIQUE INDEX "Posts_tags_key" ON public."Posts" USING btree (tags);

CREATE UNIQUE INDEX "Posts_title_key" ON public."Posts" USING btree (title);

CREATE UNIQUE INDEX "ProjectDetail_created_at_key" ON public."ProjectDetail" USING btree (created_at);

CREATE UNIQUE INDEX "ProjectDetail_image_url_key" ON public."ProjectDetail" USING btree (image_url);

CREATE UNIQUE INDEX "ProjectDetail_live_url_key" ON public."ProjectDetail" USING btree (live_url);

CREATE UNIQUE INDEX "ProjectDetail_outcomes_key" ON public."ProjectDetail" USING btree (outcomes);

CREATE UNIQUE INDEX "ProjectDetail_pkey" ON public."ProjectDetail" USING btree (id);

CREATE UNIQUE INDEX "ProjectDetail_repo_url_key" ON public."ProjectDetail" USING btree (repo_url);

CREATE UNIQUE INDEX "ProjectDetail_summary_key" ON public."ProjectDetail" USING btree (slug);

CREATE UNIQUE INDEX "ProjectDetail_tags_key" ON public."ProjectDetail" USING btree (tags);

CREATE UNIQUE INDEX "ProjectDetail_title_key" ON public."ProjectDetail" USING btree (title);

CREATE UNIQUE INDEX "Projects_date_key" ON public."Projects" USING btree (date);

CREATE UNIQUE INDEX "Projects_git_url_key" ON public."Projects" USING btree (git_url);

CREATE UNIQUE INDEX "Projects_image_url_key" ON public."Projects" USING btree (image_url);

CREATE UNIQUE INDEX "Projects_pkey" ON public."Projects" USING btree (id);

CREATE UNIQUE INDEX "Projects_proj_url_key" ON public."Projects" USING btree (proj_url);

CREATE UNIQUE INDEX "Projects_slug_key" ON public."Projects" USING btree (slug);

CREATE UNIQUE INDEX "Projects_summary_key" ON public."Projects" USING btree (summary);

CREATE UNIQUE INDEX "Projects_tags_key" ON public."Projects" USING btree (tags);

CREATE UNIQUE INDEX "Projects_title_key" ON public."Projects" USING btree (title);

CREATE UNIQUE INDEX "Subscribers_pkey" ON public."Subscribers" USING btree (id);

CREATE UNIQUE INDEX research_entries_pkey ON public.research_entries USING btree (id);

alter table "public"."BlogDetail" add constraint "BlogDetail_pkey" PRIMARY KEY using index "BlogDetail_pkey";

alter table "public"."Mails" add constraint "Mails_pkey" PRIMARY KEY using index "Mails_pkey";

alter table "public"."Posts" add constraint "Posts_pkey" PRIMARY KEY using index "Posts_pkey";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_pkey" PRIMARY KEY using index "ProjectDetail_pkey";

alter table "public"."Projects" add constraint "Projects_pkey" PRIMARY KEY using index "Projects_pkey";

alter table "public"."Subscribers" add constraint "Subscribers_pkey" PRIMARY KEY using index "Subscribers_pkey";

alter table "public"."research_entries" add constraint "research_entries_pkey" PRIMARY KEY using index "research_entries_pkey";

alter table "public"."BlogDetail" add constraint "BlogDetail_date_fkey" FOREIGN KEY (date) REFERENCES public."Posts"(date) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."BlogDetail" validate constraint "BlogDetail_date_fkey";

alter table "public"."BlogDetail" add constraint "BlogDetail_gallery_key" UNIQUE using index "BlogDetail_gallery_key";

alter table "public"."BlogDetail" add constraint "BlogDetail_id_fkey" FOREIGN KEY (id) REFERENCES public."Posts"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."BlogDetail" validate constraint "BlogDetail_id_fkey";

alter table "public"."BlogDetail" add constraint "BlogDetail_media_url_fkey" FOREIGN KEY (media_url) REFERENCES public."Posts"(media_url) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."BlogDetail" validate constraint "BlogDetail_media_url_fkey";

alter table "public"."BlogDetail" add constraint "BlogDetail_slug_fkey" FOREIGN KEY (slug) REFERENCES public."Posts"(slug) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."BlogDetail" validate constraint "BlogDetail_slug_fkey";

alter table "public"."BlogDetail" add constraint "BlogDetail_slug_key" UNIQUE using index "BlogDetail_slug_key";

alter table "public"."BlogDetail" add constraint "BlogDetail_summary_fkey" FOREIGN KEY (summary) REFERENCES public."Posts"(summary) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."BlogDetail" validate constraint "BlogDetail_summary_fkey";

alter table "public"."BlogDetail" add constraint "BlogDetail_summary_key" UNIQUE using index "BlogDetail_summary_key";

alter table "public"."BlogDetail" add constraint "BlogDetail_tags_fkey" FOREIGN KEY (tags) REFERENCES public."Posts"(tags) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."BlogDetail" validate constraint "BlogDetail_tags_fkey";

alter table "public"."BlogDetail" add constraint "BlogDetail_tags_key" UNIQUE using index "BlogDetail_tags_key";

alter table "public"."BlogDetail" add constraint "BlogDetail_title_fkey" FOREIGN KEY (title) REFERENCES public."Posts"(title) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."BlogDetail" validate constraint "BlogDetail_title_fkey";

alter table "public"."BlogDetail" add constraint "BlogDetail_title_key" UNIQUE using index "BlogDetail_title_key";

alter table "public"."Posts" add constraint "Posts_date_key" UNIQUE using index "Posts_date_key";

alter table "public"."Posts" add constraint "Posts_media_url_key" UNIQUE using index "Posts_media_url_key";

alter table "public"."Posts" add constraint "Posts_slug_key" UNIQUE using index "Posts_slug_key";

alter table "public"."Posts" add constraint "Posts_summary_key" UNIQUE using index "Posts_summary_key";

alter table "public"."Posts" add constraint "Posts_tags_key" UNIQUE using index "Posts_tags_key";

alter table "public"."Posts" add constraint "Posts_title_key" UNIQUE using index "Posts_title_key";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_created_at_fkey" FOREIGN KEY (created_at) REFERENCES public."Projects"(date) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."ProjectDetail" validate constraint "ProjectDetail_created_at_fkey";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_created_at_key" UNIQUE using index "ProjectDetail_created_at_key";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_image_url_fkey" FOREIGN KEY (image_url) REFERENCES public."Projects"(image_url) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."ProjectDetail" validate constraint "ProjectDetail_image_url_fkey";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_image_url_key" UNIQUE using index "ProjectDetail_image_url_key";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_live_url_fkey" FOREIGN KEY (live_url) REFERENCES public."Projects"(proj_url) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."ProjectDetail" validate constraint "ProjectDetail_live_url_fkey";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_live_url_key" UNIQUE using index "ProjectDetail_live_url_key";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_outcomes_key" UNIQUE using index "ProjectDetail_outcomes_key";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_repo_url_fkey" FOREIGN KEY (repo_url) REFERENCES public."Projects"(git_url) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."ProjectDetail" validate constraint "ProjectDetail_repo_url_fkey";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_repo_url_key" UNIQUE using index "ProjectDetail_repo_url_key";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_slug_fkey" FOREIGN KEY (slug) REFERENCES public."Projects"(slug) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."ProjectDetail" validate constraint "ProjectDetail_slug_fkey";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_summary_key" UNIQUE using index "ProjectDetail_summary_key";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_tags_fkey" FOREIGN KEY (tags) REFERENCES public."Projects"(tags) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."ProjectDetail" validate constraint "ProjectDetail_tags_fkey";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_tags_key" UNIQUE using index "ProjectDetail_tags_key";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_title_fkey" FOREIGN KEY (title) REFERENCES public."Projects"(title) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."ProjectDetail" validate constraint "ProjectDetail_title_fkey";

alter table "public"."ProjectDetail" add constraint "ProjectDetail_title_key" UNIQUE using index "ProjectDetail_title_key";

alter table "public"."Projects" add constraint "Projects_date_key" UNIQUE using index "Projects_date_key";

alter table "public"."Projects" add constraint "Projects_git_url_key" UNIQUE using index "Projects_git_url_key";

alter table "public"."Projects" add constraint "Projects_image_url_key" UNIQUE using index "Projects_image_url_key";

alter table "public"."Projects" add constraint "Projects_proj_url_key" UNIQUE using index "Projects_proj_url_key";

alter table "public"."Projects" add constraint "Projects_slug_key" UNIQUE using index "Projects_slug_key";

alter table "public"."Projects" add constraint "Projects_summary_key" UNIQUE using index "Projects_summary_key";

alter table "public"."Projects" add constraint "Projects_tags_key" UNIQUE using index "Projects_tags_key";

alter table "public"."Projects" add constraint "Projects_title_key" UNIQUE using index "Projects_title_key";

alter table "public"."research_entries" add constraint "research_entries_kind_check" CHECK ((kind = ANY (ARRAY['experience'::text, 'publication'::text, 'note'::text, 'replication'::text]))) not valid;

alter table "public"."research_entries" validate constraint "research_entries_kind_check";

grant delete on table "public"."BlogDetail" to "anon";

grant insert on table "public"."BlogDetail" to "anon";

grant references on table "public"."BlogDetail" to "anon";

grant select on table "public"."BlogDetail" to "anon";

grant trigger on table "public"."BlogDetail" to "anon";

grant truncate on table "public"."BlogDetail" to "anon";

grant update on table "public"."BlogDetail" to "anon";

grant delete on table "public"."BlogDetail" to "authenticated";

grant insert on table "public"."BlogDetail" to "authenticated";

grant references on table "public"."BlogDetail" to "authenticated";

grant select on table "public"."BlogDetail" to "authenticated";

grant trigger on table "public"."BlogDetail" to "authenticated";

grant truncate on table "public"."BlogDetail" to "authenticated";

grant update on table "public"."BlogDetail" to "authenticated";

grant delete on table "public"."BlogDetail" to "service_role";

grant insert on table "public"."BlogDetail" to "service_role";

grant references on table "public"."BlogDetail" to "service_role";

grant select on table "public"."BlogDetail" to "service_role";

grant trigger on table "public"."BlogDetail" to "service_role";

grant truncate on table "public"."BlogDetail" to "service_role";

grant update on table "public"."BlogDetail" to "service_role";

grant delete on table "public"."Mails" to "anon";

grant insert on table "public"."Mails" to "anon";

grant references on table "public"."Mails" to "anon";

grant select on table "public"."Mails" to "anon";

grant trigger on table "public"."Mails" to "anon";

grant truncate on table "public"."Mails" to "anon";

grant update on table "public"."Mails" to "anon";

grant delete on table "public"."Mails" to "authenticated";

grant insert on table "public"."Mails" to "authenticated";

grant references on table "public"."Mails" to "authenticated";

grant select on table "public"."Mails" to "authenticated";

grant trigger on table "public"."Mails" to "authenticated";

grant truncate on table "public"."Mails" to "authenticated";

grant update on table "public"."Mails" to "authenticated";

grant delete on table "public"."Mails" to "service_role";

grant insert on table "public"."Mails" to "service_role";

grant references on table "public"."Mails" to "service_role";

grant select on table "public"."Mails" to "service_role";

grant trigger on table "public"."Mails" to "service_role";

grant truncate on table "public"."Mails" to "service_role";

grant update on table "public"."Mails" to "service_role";

grant delete on table "public"."Posts" to "anon";

grant insert on table "public"."Posts" to "anon";

grant references on table "public"."Posts" to "anon";

grant select on table "public"."Posts" to "anon";

grant trigger on table "public"."Posts" to "anon";

grant truncate on table "public"."Posts" to "anon";

grant update on table "public"."Posts" to "anon";

grant delete on table "public"."Posts" to "authenticated";

grant insert on table "public"."Posts" to "authenticated";

grant references on table "public"."Posts" to "authenticated";

grant select on table "public"."Posts" to "authenticated";

grant trigger on table "public"."Posts" to "authenticated";

grant truncate on table "public"."Posts" to "authenticated";

grant update on table "public"."Posts" to "authenticated";

grant delete on table "public"."Posts" to "service_role";

grant insert on table "public"."Posts" to "service_role";

grant references on table "public"."Posts" to "service_role";

grant select on table "public"."Posts" to "service_role";

grant trigger on table "public"."Posts" to "service_role";

grant truncate on table "public"."Posts" to "service_role";

grant update on table "public"."Posts" to "service_role";

grant delete on table "public"."ProjectDetail" to "anon";

grant insert on table "public"."ProjectDetail" to "anon";

grant references on table "public"."ProjectDetail" to "anon";

grant select on table "public"."ProjectDetail" to "anon";

grant trigger on table "public"."ProjectDetail" to "anon";

grant truncate on table "public"."ProjectDetail" to "anon";

grant update on table "public"."ProjectDetail" to "anon";

grant delete on table "public"."ProjectDetail" to "authenticated";

grant insert on table "public"."ProjectDetail" to "authenticated";

grant references on table "public"."ProjectDetail" to "authenticated";

grant select on table "public"."ProjectDetail" to "authenticated";

grant trigger on table "public"."ProjectDetail" to "authenticated";

grant truncate on table "public"."ProjectDetail" to "authenticated";

grant update on table "public"."ProjectDetail" to "authenticated";

grant delete on table "public"."ProjectDetail" to "service_role";

grant insert on table "public"."ProjectDetail" to "service_role";

grant references on table "public"."ProjectDetail" to "service_role";

grant select on table "public"."ProjectDetail" to "service_role";

grant trigger on table "public"."ProjectDetail" to "service_role";

grant truncate on table "public"."ProjectDetail" to "service_role";

grant update on table "public"."ProjectDetail" to "service_role";

grant delete on table "public"."Projects" to "anon";

grant insert on table "public"."Projects" to "anon";

grant references on table "public"."Projects" to "anon";

grant select on table "public"."Projects" to "anon";

grant trigger on table "public"."Projects" to "anon";

grant truncate on table "public"."Projects" to "anon";

grant update on table "public"."Projects" to "anon";

grant delete on table "public"."Projects" to "authenticated";

grant insert on table "public"."Projects" to "authenticated";

grant references on table "public"."Projects" to "authenticated";

grant select on table "public"."Projects" to "authenticated";

grant trigger on table "public"."Projects" to "authenticated";

grant truncate on table "public"."Projects" to "authenticated";

grant update on table "public"."Projects" to "authenticated";

grant delete on table "public"."Projects" to "service_role";

grant insert on table "public"."Projects" to "service_role";

grant references on table "public"."Projects" to "service_role";

grant select on table "public"."Projects" to "service_role";

grant trigger on table "public"."Projects" to "service_role";

grant truncate on table "public"."Projects" to "service_role";

grant update on table "public"."Projects" to "service_role";

grant delete on table "public"."Subscribers" to "anon";

grant insert on table "public"."Subscribers" to "anon";

grant references on table "public"."Subscribers" to "anon";

grant select on table "public"."Subscribers" to "anon";

grant trigger on table "public"."Subscribers" to "anon";

grant truncate on table "public"."Subscribers" to "anon";

grant update on table "public"."Subscribers" to "anon";

grant delete on table "public"."Subscribers" to "authenticated";

grant insert on table "public"."Subscribers" to "authenticated";

grant references on table "public"."Subscribers" to "authenticated";

grant select on table "public"."Subscribers" to "authenticated";

grant trigger on table "public"."Subscribers" to "authenticated";

grant truncate on table "public"."Subscribers" to "authenticated";

grant update on table "public"."Subscribers" to "authenticated";

grant delete on table "public"."Subscribers" to "service_role";

grant insert on table "public"."Subscribers" to "service_role";

grant references on table "public"."Subscribers" to "service_role";

grant select on table "public"."Subscribers" to "service_role";

grant trigger on table "public"."Subscribers" to "service_role";

grant truncate on table "public"."Subscribers" to "service_role";

grant update on table "public"."Subscribers" to "service_role";

grant delete on table "public"."research_entries" to "anon";

grant insert on table "public"."research_entries" to "anon";

grant references on table "public"."research_entries" to "anon";

grant select on table "public"."research_entries" to "anon";

grant trigger on table "public"."research_entries" to "anon";

grant truncate on table "public"."research_entries" to "anon";

grant update on table "public"."research_entries" to "anon";

grant delete on table "public"."research_entries" to "authenticated";

grant insert on table "public"."research_entries" to "authenticated";

grant references on table "public"."research_entries" to "authenticated";

grant select on table "public"."research_entries" to "authenticated";

grant trigger on table "public"."research_entries" to "authenticated";

grant truncate on table "public"."research_entries" to "authenticated";

grant update on table "public"."research_entries" to "authenticated";

grant delete on table "public"."research_entries" to "service_role";

grant insert on table "public"."research_entries" to "service_role";

grant references on table "public"."research_entries" to "service_role";

grant select on table "public"."research_entries" to "service_role";

grant trigger on table "public"."research_entries" to "service_role";

grant truncate on table "public"."research_entries" to "service_role";

grant update on table "public"."research_entries" to "service_role";


  create policy "Public can read published posts"
  on "public"."Posts"
  as permissive
  for select
  to anon, authenticated
using ((published = true));



